function Hd = filtro_fir
%FILTRO_FIR Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 9.12 and DSP System Toolbox 9.14.
% Generated on: 22-May-2022 19:44:26

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 50000;  % Sampling Frequency

Fpass = 3000;           % Passband Frequency
Fstop = 5000;           % Stopband Frequency
Dpass = 0.11462326752;  % Passband Ripple
Dstop = 0.0001;         % Stopband Attenuation
dens  = 20;             % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fpass, Fstop]/(Fs/2), [1 0], [Dpass, Dstop]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
Hd = dfilt.dffir(b);

% [EOF]
